# @format

on: [push]

jobs:
  test_one_issues:
    runs-on: ubuntu-latest
    name: create issues action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./script
      - name: commit
        run: |
          git config --global user.email "zyj17715640603@gmail.com"
          git config --global user.name  "Jack-Zhang-1314"
          git add .
          git commit -m "generated"
          git push origin main
